
import 'package:flutter/material.dart'; import 'models/product.dart'; import 'services/app_repository.dart'; import 'services/settings_service.dart'; import 'screens/dashboard_screen.dart'; import 'screens/product_screen.dart'; import 'screens/sale_screen.dart'; import 'screens/history_screen.dart'; import 'screens/settings_screen.dart'; import 'screens/lock_screen.dart'; import 'widgets/app_header.dart';
void main(){ runApp(const UltraApp()); }
class UltraApp extends StatefulWidget{ const UltraApp({super.key}); @override State<UltraApp> createState()=>_State();}
class _State extends State<UltraApp>{ final repo=AppRepository(); final settings=SettingsService(); int tab=0; bool ready=false; bool unlocked=true; bool dark=false;
  @override void initState(){super.initState(); _init();}
  Future<void> _init() async { await repo.load(); dark=await settings.getDarkMode(); final pin=await settings.getPin(); unlocked=pin==null||pin.isEmpty; setState(()=>ready=true); }
  ThemeData _theme(bool d)=>ThemeData(brightness: d?Brightness.dark:Brightness.light, colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFFFF8C00), brightness: d?Brightness.dark:Brightness.light), useMaterial3: true, inputDecorationTheme: const InputDecorationTheme(border: OutlineInputBorder()));
  @override Widget build(BuildContext context){ if(!ready) return const MaterialApp(home: Scaffold(body: Center(child: CircularProgressIndicator())));
    return MaterialApp(debugShowCheckedModeBanner:false, theme:_theme(dark), home: FutureBuilder<String?>(future: settings.getPin(), builder: (c,s){final pin=s.data??''; if(!unlocked && pin.isNotEmpty){ return LockScreen(pin: pin, onUnlocked: ()=>setState(()=>unlocked=true)); }
      return Scaffold(appBar: AppHeader(title: _title()), body: _body(), bottomNavigationBar: NavigationBar(selectedIndex: tab, destinations: const [ NavigationDestination(icon: Icon(Icons.home), label: 'Accueil'), NavigationDestination(icon: Icon(Icons.inventory_2), label: 'Gérer produit'), NavigationDestination(icon: Icon(Icons.point_of_sale), label: 'Vente'), NavigationDestination(icon: Icon(Icons.history), label: 'Historique'), NavigationDestination(icon: Icon(Icons.settings), label: 'Paramètres') ], onDestinationSelected: (i)=>setState(()=>tab=i)); );}); }
  String _title()=> ['Tableau de bord','Gestion des produits','Vente & Facturation','Historique des ventes','Paramètres'][tab];
  Widget _body(){ switch(tab){ case 0: return DashboardScreen(products: repo.products, onGoProducts: ()=>setState(()=>tab=1), onGoSales: ()=>setState(()=>tab=2), onGoHistory: ()=>setState(()=>tab=3)); case 1: return ProductScreen(products: repo.products, onSave: (p) async {await repo.addOrUpdateProduct(p); setState((){});}, onDeleteAll: () async {await repo.deleteAllProducts(); setState((){});}, onHome: ()=>setState(()=>tab=0)); case 2: return SaleScreen(products: repo.products, onSale: (p,q,city,name,phone,date) async { await repo.createSale(product: p, quantity: q, city: city, clientName: name, clientPhone: phone, date: date); setState((){});}, onHome: ()=>setState(()=>tab=0)); case 3: return HistoryScreen(onHome: ()=>setState(()=>tab=0)); default: return SettingsScreen(settings: settings, onApplied: () async { dark=await settings.getDarkMode(); setState((){});}); } }
}
